{% set name = "gazebo" %}
{% set version = "11.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://bitbucket.org/osrf/{{ name }}/get/{{ name }}{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: f1c873dfa17c1653332321ef4f10430fb22825de0688017455a2983f176cd69e
    patches:
      - use-external-libs-config.patch
      - qwt-fix.patch
      - normalize-ogre-path.patch

build:
  number: 2
  skip: true  # [not win]
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - ninja
    - cmake
    - pkg-config
  host:
    - libsdformat 9.*
    - libignition-transport8
    - libignition-fuel-tools4
    - libignition-common3
    - qt
    - ogre
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - dlfcn-win32  # [win]
    - boost-cpp >=1.71
  run:
    - libsdformat 9.*
    - libignition-transport8
    - libignition-fuel-tools4
    - libignition-common3
    - qt
    - ogre
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - dlfcn-win32  # [win]
    - boost-cpp >=1.71

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\gzserver.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gzclient.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gazebo.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Advanced robot simulator for research, design, and development.'

extra:
  recipe-maintainers:
    - seanyen
