{% set name = "gazebo" %}
{% set version = "11.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/{{ name }}/archive/{{ name }}{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: b3c14fc1a123be2992b880efa11d362d3d06c77d8c9624a14c487357ec7623f1
    patches:
      - fix_build.patch  # [unix]
      - use-external-libs-config.patch
      - normalize-ogre-path.patch
      - cmake_129_workaround.patch  # [unix]
      - 2906.patch

build:
  number: 4
  skip: false
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake 3.16.*
    - pkg-config
    - ninja

    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [unix]
    - {{ cdt('mesa-dri-drivers') }}  # [unix]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
  host:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - libprotobuf
    - libsdformat
    - libignition-cmake2
    - libignition-math6
    - libignition-transport8
    - libignition-common3 
    - libignition-fuel-tools4
    - qt
    - ogre 1.10.*
    - freeimage
    - curl
    - tbb-devel  # [not win]
    - tbb-devel 2019.9  # [win]
    - qwt
    - tinyxml2
    - libtar   # [unix]
    - libccd   # [unix]
    # - hdf5     # [linux]
    # - simbody  # [linux]
    - dlfcn-win32  # [win]
    - boost-cpp
    # additional deps
    - libuuid  # [linux]
    - libcurl
    - tinyxml
    # - gts
    - bzip2  # [osx]
    - zlib  # [osx]
    - tiny-process-library  # [win]
    - ffmpeg

  run:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - libprotobuf
    - qt
    - ogre
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - tinyxml2
    - libtar   # [unix]
    - libccd   # [unix]
    # - hdf5     # [linux]
    # - simbody  # [linux]
    # - gts
    - dlfcn-win32  # [win]
    - boost-cpp
    - libuuid  # [linux]
    - libcurl
    - tinyxml
    - bzip2  # [osx]
    - zlib  # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\gzserver.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gzclient.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gazebo.exe (exit 0) else (exit 1)  # [win]
    - test -f $PREFIX/bin/gzserver  # [unix]
    - test -f $PREFIX/bin/gzclient  # [unix]
    - test -f $PREFIX/bin/gazebo    # [unix]

about:
  home: http://gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Advanced robot simulator for research, design, and development.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
