{% set name = "gazebo" %}
{% set version = "11.15.1" %}
{% set build_number = 6 %}

{% if GZ_CLI_NAME_VARIANT == "origname" %}
{% set build_number = build_number + 200 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/{{ name }}/archive/{{ name }}{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 77a952971eabfd79e16d2582a355ee017a2e22cc369b68453323c0984b725126
    patches:
      - use-external-libs-config.patch
      - fix-invisible-meshes.patch
      - protobuf30.patch

build:
  number: {{ build_number }}
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x') }}
  string: {{ GZ_CLI_NAME_VARIANT }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - pkg-config
    - ninja

    # We need all host deps also in build for cross-compiling gazebomsgs_out
    - libabseil  # [build_platform != target_platform]
    - libprotobuf  # [build_platform != target_platform]
    - libsdformat 9.*  # [build_platform != target_platform]
    - libignition-cmake2  # [build_platform != target_platform]
    - libignition-math6  # [build_platform != target_platform]
    - libignition-transport8  # [build_platform != target_platform]
    - libignition-common3  # [build_platform != target_platform]
    - libignition-fuel-tools4  # [build_platform != target_platform]
    - ogre 1.10.*  # [build_platform != target_platform]
    - qt-main  # [build_platform != target_platform]
    - freeimage  # [build_platform != target_platform]
    - curl  # [build_platform != target_platform]
    - tbb-devel  # [build_platform != target_platform]
    - qwt  # [build_platform != target_platform]
    - tinyxml2  # [build_platform != target_platform]
    - libtar  # [build_platform != target_platform]
    - libccd-double  # [build_platform != target_platform]
    - libboost-devel  # [build_platform != target_platform]
  host:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    - libgl-devel       # [linux]
    # deps
    - libabseil
    - libprotobuf
    - libsdformat 9.*
    - libignition-cmake2
    - libignition-math6
    - libignition-transport8
    - libignition-common3
    # Workaround for https://github.com/conda-forge/gazebo-feedstock/pull/143
    - libignition-fuel-tools4 >=4.6
    - libignition-msgs5
    - ogre 1.10.*
    - qt-main
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - tinyxml2
    - libtar   # [unix]
    - libccd-double
    - dlfcn-win32  # [win]
    - libboost-devel
    # additional deps
    - libuuid  # [linux]
    - libcurl
    - tinyxml
    # - gts
    - bzip2  # [osx]
    - zlib  # [osx]
    - tiny-process-library  # [win]
    - ffmpeg
    - graphviz
    - libgdal
    - libusb
    # Bullet is not detected on win for some reason
    - bullet-cpp  # [not win]
    - dartsim-cpp
    - simbody
    - hdf5
    - openal-soft
    - libode
    - assimp
    - urdfdom
    - libblas
    - libcblas

  run:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - libboost-devel
    - tbb-devel
    # Add constraint to avoid that old ogre gets installed during migratons,
    # see https://github.com/conda-forge/gazebo-feedstock/pull/188/files and
    # https://github.com/conda-forge/gazebo-feedstock/pull/203#issuecomment-1981995139
    - "ogre >=1.10.12.1"
  run_constrained:
    # Prevent to install side-by-side installation with libgz-tools2
    - libgz-tools2 <0.0.0  # [GZ_CLI_NAME_VARIANT == "origname"]

test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\gzserver.exe  exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\gzclient.exe  exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\gazebo.exe exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\gz.exe exit 1  # [win and GZ_CLI_NAME_VARIANT == "origname"]
    - if not exist %PREFIX%\\Library\\bin\\gz11.exe exit 1  # [win]
    - test -f $PREFIX/bin/gzserver  # [unix]
    - test -f $PREFIX/bin/gzclient  # [unix]
    - test -f $PREFIX/bin/gazebo    # [unix]
    - test -f $PREFIX/bin/gz  # [unix and GZ_CLI_NAME_VARIANT == "origname"]
    - test -f $PREFIX/bin/gz11  # [unix]
    - test -f $PREFIX/lib/libCameraPlugin.dylib  # [osx]
    - gzserver --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    - gzclient --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    - gazebo --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    # We do not try to check the gz11 help output as it prints on stderr and not stdout
    # For some reason this fails on aarch64 with Error setting socket option (IP_MULTICAST_IF) error
    - gz11 help  # [not aarch64]

about:
  home: http://classic.gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Gazebo Classic robot simulator for research, design, and development.
  description: |
    This feedstock packages the Gazebo Classic simulator, that will not be supported past 2025. 
    For new development, please consider migrating to Modern gz-sim simulator, available in conda-forge.
    To simplify migration to gz-sim, we want to permit to side-by-side installation of gazebo and libgz-tools2, however they both install a command called `gz`. 
    So, this feedstock is building two different variants of the `gazebo` conda package:
      * One that contains `origname` in its build string that has higher priority and is installed if libgz-tools2 is not installed, that uses `gz` as the name for the cli helper of gazebo classic. This variant cannot be installed if `libgz-tools2` is installed. For forward compatibility, this variant also installs a `gz11` command.
      * One that contains `gzcompatname` that is co-installable with libgz-tools2, but that renames the `gz` commmand line tool to `gz11`.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
    - traversaro
