{% set name = "gazebo" %}
{% set version = "11.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/{{ name }}/archive/{{ name }}{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 6b63d857399ba08190c331b545d24e8e3e308b840ff051bbf39e87879e37af50
    patches:
      - use-external-libs-config.patch
      - fix-invisible-meshes.patch
      - 3347.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17  # [linux64 and cdt_name == 'cos7']
    - cmake
    - pkg-config
    - ninja

    # x11 stuff
    - {{ cdt('mesa-libgl') }}        # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [unix and not arm64]
    - {{ cdt('mesa-dri-drivers') }}  # [unix and not arm64]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
    # We need all host deps also in build for cross-compiling gazebomsgs_out
    - libabseil  # [build_platform != target_platform]
    - libprotobuf  # [build_platform != target_platform]
    - libsdformat  # [build_platform != target_platform]
    - libignition-cmake2  # [build_platform != target_platform]
    - libignition-math6  # [build_platform != target_platform]
    - libignition-transport8  # [build_platform != target_platform]
    - libignition-common3  # [build_platform != target_platform]
    - libignition-fuel-tools4  # [build_platform != target_platform]
    - ogre 1.10.*  # [build_platform != target_platform]
    - qt-main  # [build_platform != target_platform]
    - freeimage  # [build_platform != target_platform]
    - curl  # [build_platform != target_platform]
    - tbb-devel  # [build_platform != target_platform]
    - qwt  # [build_platform != target_platform]
    - tinyxml2  # [build_platform != target_platform]
    - libtar  # [build_platform != target_platform]
    - libccd-double  # [build_platform != target_platform]
    - libboost-devel  # [build_platform != target_platform]
  host:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - libabseil
    - libprotobuf
    - libsdformat
    - libignition-cmake2
    - libignition-math6
    - libignition-transport8
    - libignition-common3
    # Workaround for https://github.com/conda-forge/gazebo-feedstock/pull/143
    - libignition-fuel-tools4 >=4.6
    - libignition-msgs5
    - ogre 1.10.*
    - qt-main
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - tinyxml2
    - libtar   # [unix]
    - libccd-double
    - dlfcn-win32  # [win]
    - libboost-devel
    # additional deps
    - libuuid  # [linux]
    - libcurl
    - tinyxml
    # - gts
    - bzip2  # [osx]
    - zlib  # [osx]
    - tiny-process-library  # [win]
    - ffmpeg
    - graphviz
    - libgdal
    - libusb
    # Bullet is not detected on win for some reason
    - bullet-cpp  # [not win]
    - dartsim
    - simbody
    - hdf5
    - openal-soft
    - libode
    - assimp
    - urdfdom
    - libblas
    - libcblas

  run:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - libboost-devel
    - tbb-devel
    # Add constraint to avoid that old ogre gets installed during migratons,
    # see https://github.com/conda-forge/gazebo-feedstock/pull/188/files
    - "ogre >=1.10.12[build_number=3]"
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\gzserver.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gzclient.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gazebo.exe (exit 0) else (exit 1)  # [win]
    - test -f $PREFIX/bin/gzserver  # [unix]
    - test -f $PREFIX/bin/gzclient  # [unix]
    - test -f $PREFIX/bin/gazebo    # [unix]
    - gzserver --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    - gzclient --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    - gazebo --version | grep "Gazebo multi-robot simulator, version"  # [unix]

about:
  home: http://gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Advanced robot simulator for research, design, and development.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
    - traversaro
