{% set name = "gazebo" %}
{% set version = "9.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:

  - url: https://github.com/osrf/{{ name }}/archive/{{ name }}{{ version[0] }}_{{ version }}.tar.gz
    sha256: 8a616a83b7dd0d919adbceaa3bef22e051186fe6e9698dd245a9a29a0c97502e
    patches:
      - use-external-libs-config.patch
      - qwt-fix.patch  # [win]
      - normalize-ogre-path.patch
      - fix_build.patch  # [unix]

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - ninja
    - cmake
    - pkg-config

    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [unix]
    - {{ cdt('mesa-dri-drivers') }}  # [unix]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
  host:
    - libsdformat 6.*
    - libignition-transport4
    - qt 5.12.5
    - ogre 1.10.12
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - dlfcn-win32  # [win]
    - boost-cpp
    - bzip2      # [osx]
    - zlib       # [osx]
    - tinyxml2
    - libtar     # [unix]
    - libccd     # [unix]
    # - libspnav   # [unix]
  run:
    - libsdformat 6.*
    - libignition-transport4
    - qt 5.12.5
    - ogre 1.10.12
    - freeimage
    - curl
    - tbb-devel
    - qwt
    - dlfcn-win32  # [win]
    - boost-cpp
    # - libspnav   # [unix]


test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\gzserver.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gzclient.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gazebo.dll (exit 0) else (exit 1)  # [win]

about:
  home: http://gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Advanced robot simulator for research, design, and development.'

extra:
  recipe-maintainers:
    - seanyen
