{% set name = "gazebo" %}
{% set version = "11.10.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/osrf/{{ name }}/archive/{{ name }}{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 4988e004952942489c4c011e4a8f86ada0690aa09a5b3c1cd37230c33d69b67c
    patches:
      - fix_build.patch  # [unix]
      - use-external-libs-config.patch
      - normalize-ogre-path.patch
      - fix-invisible-meshes.patch
      # for tbb2021 compatibility
      - 3146.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('gazebo', max_pin='x') }}

  {% if OGRE_VERSION == "1.12" %}
  track_features:
    - gazebo_classic_with_ogre_1_12
  {% endif %}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake 3.16.*
    - pkg-config
    - ninja

    # x11 stuff
    - {{ cdt('mesa-libgl-devel') }}  # [unix]
    - {{ cdt('mesa-dri-drivers') }}  # [unix]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('expat-devel') }}       # [linux]
  host:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - libprotobuf
    - libsdformat
    - libignition-cmake2
    - libignition-math6
    - libignition-transport8
    - libignition-common3
    - libignition-fuel-tools4
    - qt
    {% if OGRE_VERSION == "1.10" %}
    - ogre 1.10.*
    {% else %}
    - ogre 1.12.*
    {% endif %}

    - freeimage
    - curl
    - tbb-devel
    - qwt
    - tinyxml2
    - libtar   # [unix]
    - libccd   # [unix]
    - dlfcn-win32  # [win]
    - boost-cpp
    # additional deps
    - libuuid  # [linux]
    - libcurl
    - tinyxml
    # - gts
    - bzip2  # [osx]
    - zlib  # [osx]
    - tiny-process-library  # [win]
    - ffmpeg
    # graphviz is not found on win
    - graphviz  # [not win]
    - libgdal
    - libusb
    # Bullet is not detected on win for some reason
    - bullet-cpp  # [not win]
    # A few compile errors on Win when trying to include dartsim
    - dartsim  # [not win]
    - simbody
    - hdf5
    - openal-soft
    - libode

  run:
    - xorg-libxext      # [unix]
    - xorg-libxdmcp     # [unix]
    - xorg-libxau       # [unix]
    - libxcb            # [unix]
    - xorg-libxfixes    # [unix]
    - xorg-libxrender   # [unix]
    - xorg-libx11       # [unix]
    - xorg-libice       # [unix]
    - xorg-libsm        # [unix]
    - libglu            # [linux]
    # deps
    - boost-cpp
    - tbb-devel
    # graphviz is not found on win
    - graphviz  # [not win]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - if exist %PREFIX%\\Library\\bin\\gzserver.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gzclient.exe (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\bin\\gazebo.exe (exit 0) else (exit 1)  # [win]
    - test -f $PREFIX/bin/gzserver  # [unix]
    - test -f $PREFIX/bin/gzclient  # [unix]
    - test -f $PREFIX/bin/gazebo    # [unix]
    - gzserver --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    - gzclient --version | grep "Gazebo multi-robot simulator, version"  # [unix]
    - gazebo --version | grep "Gazebo multi-robot simulator, version"  # [unix]

about:
  home: http://gazebosim.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Advanced robot simulator for research, design, and development.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - Tobias-Fischer
    - traversaro
