azure:
  store_build_artifacts: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
# Workaround for https://github.com/conda/conda-libmamba-solver/issues/446
conda_build_tool: conda-build+classic
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
test_on_native_only: true
